package acpclient

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"path"
	"strconv"
	"strings"
	"text/template"

	"github.com/memohai/memoh/internal/workspace/bridge"
)

const (
	codexAgentID               = "codex"
	codexManagedProviderID     = "OpenAI"
	codexManagedProviderName   = "OpenAI"
	codexDefaultOpenAIBaseURL  = "https://api.openai.com/v1"
	codexManagedConfigTemplate = `# Generated by Memoh for managed Codex ACP sessions.
model_provider = {{ tomlString .ProviderID }}

[model_providers.{{ .ProviderID }}]
name = {{ tomlString .ProviderName }}
base_url = {{ tomlString .BaseURL }}
wire_api = "responses"
requires_openai_auth = false
`
)

// CodexManagedConfigDir is the standard Codex config directory inside the
// managed container workspace.
const CodexManagedConfigDir = dataMountPath + "/.codex"

var codexConfigTemplate = template.Must(template.New("codex-managed-config").
	Funcs(template.FuncMap{"tomlString": strconv.Quote}).
	Parse(codexManagedConfigTemplate))

type codexManagedConfigData struct {
	ProviderID   string
	ProviderName string
	BaseURL      string
}

// WriteCodexManagedConfig writes the fixed Codex config.toml and auth.json
// used by Memoh-managed Codex ACP sessions.
func WriteCodexManagedConfig(ctx context.Context, client *bridge.Client, managed map[string]string) error {
	if client == nil {
		return errors.New("workspace bridge client is required")
	}
	content, err := renderCodexManagedConfig(managed)
	if err != nil {
		return fmt.Errorf("render Codex config: %w", err)
	}
	auth, err := renderCodexManagedAuth(managed)
	if err != nil {
		return fmt.Errorf("render Codex auth: %w", err)
	}
	if err := client.WriteFile(ctx, path.Join(CodexManagedConfigDir, "config.toml"), content); err != nil {
		return fmt.Errorf("write Codex config: %w", err)
	}
	if err := client.WriteFile(ctx, path.Join(CodexManagedConfigDir, "auth.json"), auth); err != nil {
		return fmt.Errorf("write Codex auth: %w", err)
	}
	return nil
}

func renderCodexManagedConfig(managed map[string]string) ([]byte, error) {
	baseURL := strings.TrimSpace(managed["base_url"])
	if baseURL == "" {
		baseURL = codexDefaultOpenAIBaseURL
	}

	var out bytes.Buffer
	if err := codexConfigTemplate.Execute(&out, codexManagedConfigData{
		ProviderID:   codexManagedProviderID,
		ProviderName: codexManagedProviderName,
		BaseURL:      baseURL,
	}); err != nil {
		return nil, err
	}
	return out.Bytes(), nil
}

func renderCodexManagedAuth(managed map[string]string) ([]byte, error) {
	apiKey := strings.TrimSpace(managed["api_key"])
	if apiKey == "" {
		return nil, errors.New("api_key is required")
	}
	content, err := json.MarshalIndent(map[string]string{
		"OPENAI_API_KEY": apiKey,
	}, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(content, '\n'), nil
}

func isCodexAgent(agentID string) bool {
	return strings.EqualFold(strings.TrimSpace(agentID), codexAgentID)
}
